#
# https://code.chs.usgs.gov/coupled/phreeqci
# SRC 2020-01-28T10:03:39-07:00
#
image: buildpack-deps:bionic-scm

stages:
  - sync

before_script:
  - eval $(ssh-agent -s)
  - echo "${SSH_PRIVATE_KEY_ENC}" | base64 --decode | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan ${CI_SERVER_HOST} >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - git config --global user.email "darth@empire.com"
  - git config --global user.name "Darth Vader"
 
subtree-sync:
  stage: sync

  ##
  ## Only run if on the master branch and the variable GROUP is set
  ##
  ## change this to
  ## only:
  ##  - master@$GROUP/phreeqci
  ## and set GROUP to coupled before merge
  only:
    refs:
      - master
    variables:
      - $GROUP
  
  script:
    ##
    ## Must re-clone in order for the subtree merge to work
    ## tried re-setting the url for the origin but didn't work
    ##
    - cd ..
    - rm -rf ${CI_PROJECT_NAME}
    - git clone git@${CI_SERVER_HOST}:${CI_PROJECT_PATH}.git
    - cd ${CI_PROJECT_NAME}

    ##
    ## Sync subtrees
    ##
    - |
      #!/bin/bash -ex
      #
      # phreeqci                 git@${CI_SERVER_HOST}:${GROUP}/phreeqci.git
      # ├─gridctrl               ├─git@${CI_SERVER_HOST}:${GROUP}/subtrees/wphast-src-gridctrl.git                  gridctrl
      # └─phreeqc3               └─git@${CI_SERVER_HOST}:${GROUP}/phreeqc3.git                                      phreeqc3
      #   ├─database               ├─git@${CI_SERVER_HOST}:${GROUP}/subtrees/phreeqc3-database.git                  phreeqc3/database
      #   ├─doc                    ├─git@${CI_SERVER_HOST}:${GROUP}/subtrees/phreeqc3-doc.git                       phreeqc3/doc
      #   ├─examples               ├─git@${CI_SERVER_HOST}:${GROUP}/subtrees/phreeqc3-examples.git                  phreeqc3/examples
      #   └─src                    └─git@${CI_SERVER_HOST}:${GROUP}/subtrees/phreeqc3-src.git                       phreeqc3/src
      #     └─common                 └─git@${CI_SERVER_HOST}:${GROUP}/subtrees/phreeqc3-src-common.git              phreeqc3/common

      git_subtree() {
        git subtree "${1}" --prefix="${2}" "${4}" master 2>&1 | grep -v "^[[:digit:]].*/[[:digit:]].*"
      }

      declare -A urls=( \
        ["phreeqc3"]="git@${CI_SERVER_HOST}:${GROUP}/phreeqc3.git" \
        ["wphast-src-gridctrl"]="git@${CI_SERVER_HOST}:${GROUP}/subtrees/wphast-src-gridctrl.git" \
      )

      declare -A prefixes=( \
        ["phreeqc3"]="phreeqc3" \
        ["wphast-src-gridctrl"]="gridctrl" \
      )

      export GIT_EDITOR=true

      for remote in "${!urls[@]}"; do
        git_subtree "pull" "${prefixes[$remote]}" "$remote" "${urls[$remote]}"
      done

      for remote in "${!urls[@]}"; do
        git_subtree "push" "${prefixes[$remote]}" "$remote" "${urls[$remote]}"
      done

      git push origin master
      git status

## Upstream Projects
## phreeqc3            https://code.chs.usgs.gov/coupled/phreeqc3
## wphast-src-gridctrl https://code.chs.usgs.gov/coupled/subtrees/wphast-src-gridctrl
